### ISSUE TITLE
AUR packages not installing

### ISSUE THREAD

**Issue by yehonatan2020** [ChrisTitusTech/ArchTitus#168] opened 2022-01-08 21:17 UTC
Something is wrong with the scripts, because all the pacman packages get installed, but it completes by enabling all the systemctl services etc but the aur packages dont get installed

**Comment by yehonatan2020** [comment] 2022-01-08 21:44
runuser: -- does not exist or the user entry does not contain all the required fields

**Comment by Cosipa** [comment] 2022-01-08 23:32
I have the same problem, and I would like to add that it only installs the aur packages when you manually type the username on 
`arch-chroot /mnt /usr/bin/runuser -u $username -- /home/$username/ArchTitus/2-user.sh` instead of $username. 

_So the issue seems to be that the source to setup.conf isn't working propperly past arch-chroot on the archtitus.sh_

**Comment by Zackptg5** [comment] 2022-01-09 19:59
Think the issue is that the username variable is now uppercase. Try changing all instances of `$username` to `$USERNAME`
Looks like this is an issue in archtitus.sh and 3-post-setup.sh

**Comment by yehonatan2020** [comment] 2022-01-09 20:26
Zackptg5 - you were 100 percent correct. changing $username to $USERNAME fixed it!!!

**Comment by ChrisTitusTech** [comment] 2022-01-10 00:42
Thanks Fixed in main branch!

**Closed by ChrisTitusTech** 2022-01-10 00:42 UTC
